# Generated by Django 6.0.3 on 2026-07-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_testdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='purpose',
            field=models.CharField(default='Family', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='seating_capacity',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='top_speed',
            field=models.IntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
