# Generated by Django 6.0.3 on 2026-08-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_purpose_car_seating_capacity_car_top_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='car',
            name='odometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='plate_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='advisor',
            field=models.CharField(blank=True, default='Veltrix Team', max_length=50),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='time_slot',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
